# Site settings
title: NTG Technology
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "ntg-tech.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: NTG Technology
user_description: We have experience creating tools that can be used for penetration testing.
user_title: Software Development
email: contact@ntgtech.com
twitter_username: lorem_ipsum
github_username:  NTG-Tech
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
